#!/bin/sh /etc/rc.common
#
# description: Startup/shutdown script for nodogsplash captive portal
#
# P. Kube 2007
#
# (Based on wifidog startup script
# Date    : 2004-08-25
# Version : 1.0
# Comment by that author: Could be better, but it's working as expected)
#

START=70
STOP=95

USE_PROCD=1

IPT=/usr/sbin/iptables
WD_DIR=/usr/bin
NDS_CONF=/etc/nodogsplash/nodogsplash.conf
# -s -d 5 runs in background, with level 5 (not so verbose) messages to syslog
# -f -d 7 runs in foreground, with level 7 (verbose) debug messages to terminal
OPTIONS="-s -f -d 5"

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/nodogsplash $OPTIONS
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	# nodogsplash doesn't exit fast enought, when procd terminates it.
	# otherwise procd will restart nodogsplash twice. first time starting nodogsplash fails, second time it succeeds
	sleep 1
}

status() {
	$WD_DIR/ndsctl status
}

## Test functions for ipt_mark and ipt_mac removed to improve startup time